# Descargar imagne oficial de kibana
FROM docker.elastic.co/elastic/elastic:8.16

##################### INSTALACIÓN PLUGINS #####################
# Copiar distribuibles de los plugins para instalar
#COPY ./kibana_plugins/enhancedTable-7.17.13.zip /tmp/enhancedTable-7.17.13.zip
#COPY ./kibana_plugins/coptChatbot-7.17.13.zip /tmp/coptChatbot-7.17.13.zip
#COPY ./kibana_plugins/copteroServer-7.17.13.zip /tmp/copteroServer-7.17.13.zip


USER elastic
WORKDIR /usr
